#!/bin/bash
set -e

echo "# AUTOGENERATED BY gen-ci.sh"
echo "stages:"
echo "  - test"
echo ""

if [ "$#" -gt 0 ]; then
  # Run changed app
  apps=("$@")
else
  # Run all (regular testing)
  apps=$(./bin/epmp --short 2>/dev/null || true)
fi


for app in $apps; do
  job_name="test_${app//[^a-zA-Z0-9_]/_}"
  echo "${job_name}:"
  echo "  stage: test"
  echo "  image: alt:p11"
  echo "  tags:"
  echo "    - access"
  echo "  script:"
  echo "    - cd bin"
  echo "    - ./epmu"
  echo "    - ./epmi -y wget glibc-pthread"
  echo "    - ./epm play --auto --verbose --ipfs $app"
  echo ""
done
