#!/bin/bash
set -e

echo "# AUTOGENERATED BY gen-ci.sh"
echo "stages:"
echo "  - test"
echo ""

if [ "$#" -gt 0 ]; then
  apps=("$@")        # only changed apps
else
  apps=$(./bin/epmp --short 2>/dev/null || true)  # all
fi

for app in $apps; do
  job_name="test_${app//[^a-zA-Z0-9_]/_}"
  echo "${job_name}:"
  echo "  stage: test"
  echo "  image: alt:p11"
  echo "  tags:"
  echo "    - access"
  echo "  script:"
  echo "    - bash ./tests/run_one_ci.sh $app"
  echo "  artifacts:"
  echo "    when: always"
  echo "    expire_in: 2 days"
  echo "    paths:"
  echo "      - \$CI_PROJECT_DIR/epm-play-versions"
  echo "      - \$CI_PROJECT_DIR/epm-errors"
  echo "      - \$CI_PROJECT_DIR/epm-logs"
  echo "      - \$CI_PROJECT_DIR/epm-requires"
  echo ""
done
