header()
{
  cat <<'EOF'
# AUTOGENERATED BY gen-ci.sh

EOF

  echo "stages:"
  if [ "$USE_DOWNLOAD" -eq 1 ]; then
    echo "  - download_test"
    echo "  - publish_download_logs"
  fi
  echo "  - test"
  echo "  - summary"
  echo
}
