header()
{
  cat <<'EOF'
# AUTOGENERATED BY gen-ci.sh

EOF

  echo "stages:"
  if [ "$USE_DOWNLOAD" -eq 1 ]; then
    echo "  - download_test"
    echo "  - publish_download_logs"
  fi
  echo "  - test"
  echo "  - summary"
  echo

  if [ "$USE_IPFS" -eq 1 ] || [ "$USE_IPFS_UPDATE" -eq 1 ]; then
    echo "variables:"
    if [ "$USE_IPFS" -eq 1 ]; then
      echo "  CI_USE_IPFS: \"1\""
    fi
    if [ "$USE_IPFS_UPDATE" -eq 1 ]; then
      echo "  CI_IPFS_UPDATE: \"1\""
    fi
    echo
  fi
}
