#!/bin/bash
set -e

cat <<'EOF'
# AUTOGENERATED BY gen-ci.sh

stages:
  - download_test
  - publish_download_logs
  - test
  - summary

EOF

# Get applications list
if [ "$#" -gt 0 ]; then
  apps="$@"
else
  apps=$(./bin/epmp --short 2>/dev/null)
fi

#
# -------- Stage: Download test --------
#
for app in $apps; do
  safe_app="${app//[^a-zA-Z0-9_]/_}"

  cat <<EOF
download_${safe_app}_p11:
  stage: download_test
  allow_failure: true
  image: alt:p11
  tags:
    - access
  before_script:
    - ./bin/epm -y repo set etersoft
    - ./bin/epm update
    - ./bin/epm -y install wget glibc-pthread file patool
    - ./bin/epm play --auto --ipfs kubo
  script:
    - bash ./ci/prepare_ipfs.sh ${app}
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - ipfs

EOF
done

#
# -------- Stage: Publish_download_logs --------
#
cat <<'EOF'
publish_download_logs:
  stage: publish_download_logs
  image: alt:p11
  tags:
    - access
  when: always
  dependencies:
EOF
for app in $apps; do
  safe_app="${app//[^a-zA-Z0-9_]/_}"
  cat <<EOF
    - download_${safe_app}_p11
EOF
done
cat <<'EOF'
  before_script:
    - ./bin/epm -y repo set etersoft
    - ./bin/epm update
    - ./bin/epm -y install git rsync
  script:
    - echo "Publishing logs and IPFS DB"
    - ls -R ipfs
    - bash ./ci/push-ipfs-db.sh
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - ipfs

EOF

#
# -------- Stage: test (consumers) --------
#
for app in $apps; do
  safe_app="${app//[^a-zA-Z0-9_]/_}"

  #
  # ALT sisyphus
  #
  cat <<EOF
test_${safe_app}_sisyphus:
  stage: test
  allow_failure: true
  image: alt:sisyphus
  tags:
    - access
  dependencies:
    - publish_download_logs
  before_script:
    - ./bin/epm -y repo set etersoft
    - ./bin/epm update
    - ./bin/epm -y install wget glibc-pthread file
    - mkdir -p /var/lib/eepm
    - cp ipfs/eget-ipfs-db.txt /var/lib/eepm/eget-ipfs-db.txt
  script:
    - bash ./ci/run_one_ci.sh ${app}
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - epm-results

EOF

  #
  # Debian bookworm 
  #
  cat <<EOF
test_${safe_app}_debian:
  stage: test
  allow_failure: true
  image: debian:bookworm
  tags:
    - access
  dependencies:
    - publish_download_logs
  before_script:
    - ./bin/epm update
    - ./bin/epm install -y bash wget ca-certificates coreutils file
    - mkdir -p /var/lib/eepm
    - cp ipfs/eget-ipfs-db.txt /var/lib/eepm/eget-ipfs-db.txt
  script:
    - bash ./ci/run_one_ci.sh ${app}
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - epm-results

EOF
done

#
# -------- Stage: summary --------
#
cat <<'EOF'
summary_ci:
  stage: summary
  image: alt:p11
  tags:
    - access
  when: always
  before_script:
    - ./bin/epm -y repo set etersoft
    - ./bin/epm update
    - ./bin/epm -y install git rsync
  script:
    - bash ./ci/push-results-ci.sh

EOF
