#!/bin/bash
set -e

echo "# AUTOGENERATED BY gen-ci.sh"
echo ""
echo "variables:"
echo "  CI_IPFS_DB_DIR: \"\$CI_PROJECT_DIR/.cache/ipfs/db\""
echo ""
echo "stages:"
echo "  - prepare"
echo "  - test"
echo "  - summary"
echo ""

# Determine the list of applications
if [ "$#" -gt 0 ]; then
  apps="$@"
else
  apps=$(./bin/epmp --short 2>/dev/null || true)
fi


for app in $apps; do
  safe_app="${app//[^a-zA-Z0-9_]/_}"
  #
  # -------- Stage: prepare --------
  #
  echo "prepare_${safe_app}_p11:"
  echo "  stage: prepare"
  echo "  allow_failure: true"
  echo "  image: alt:p11"
  echo "  tags:"
  echo "    - access"
  echo "  before_script:"
  echo "    - ./bin/epm -y repo set etersoft "
  echo "    - ./bin/epm update"  
  echo "    - ./bin/epm -y install wget glibc-pthread file"
  echo "    - ./bin/epm -y play kubo"
  echo "  script:"
  echo "    - bash ./ci/prepare-ipfs.sh $app"
  echo "  artifacts:"
  echo "    when: always"
  echo "    expire_in: 30 days"
  echo "    paths:"
  echo "      - ipfs"
  echo ""
  #
  # --------Stage: test (ALT p11) --------
  #
  echo "test_${safe_app}_p11:"
  echo "  stage: test"
  echo "  allow_failure: true"
  echo "  image: alt:p11"
  echo "  tags:"
  echo "    - access"
  echo "  before_script:"
  echo "    - ./bin/epm -y repo set etersoft"
  echo "    - ./bin/epm update"  
  echo "    - ./bin/epm -y install wget glibc-pthread file"
  echo "    - mkdir -p /var/lib/eepm"
  echo "    - cp ipfs/eget-ipfs-db.txt /var/lib/eepm/eget-ipfs-db.txt"
  echo "  script:"
  echo "    - bash ./ci/run_one_ci.sh $app"
  echo "  artifacts:"
  echo "    when: always"
  echo "    expire_in: 30 days"
  echo "    paths:"
  echo "      - epm-results"
  echo ""
  #
  # --------temp: Stage: test (debian bookworm, IPFS) --------
  #
  echo "test_${safe_app}_debian:"
  echo "  stage: test"
  echo "  allow_failure: true"
  echo "  image: debian:bookworm"
  echo "  tags:"
  echo "    - access"
  echo "  dependencies:"
  echo "    - prepare_${safe_app}_p11"
  echo "  before_script:"
  echo "    - ./bin/epm update"
  echo "    - ./bin/epm install -y bash wget ca-certificates coreutils file"
  echo "    - mkdir -p /var/lib/eepm"
  echo "    - cp ipfs/eget-ipfs-db.txt /var/lib/eepm/eget-ipfs-db.txt"
  echo "  script:"
  echo "    - echo \"Testing $app on Debian bookworm (IPFS mode)\""
  echo "    - bash ./ci/run_one_ci.sh $app"
  echo "  artifacts:"
  echo "    when: always"
  echo "    expire_in: 30 days"
  echo "    paths:"
  echo "      - epm-results"
  echo ""

done
#
# -------- Stage: summary --------
#
echo "summary_ci:"
echo "  stage: summary"
echo "  image: alt:p11"
echo "  tags:"
echo "    - access"
echo "  when: always"
echo "  before_script:"
echo "    - ./bin/epm -y repo set etersoft"
echo "    - ./bin/epm update"
echo "    - ./bin/epm -y install git rsync"
echo "  script:"
echo "    - bash push-results-ci.sh"
echo ""
