#!/bin/bash
set -e

cat <<'EOF'
# AUTOGENERATED BY gen-ci.sh

stages:
  - download_test
  - publish_download_logs
  - test
  - summary

EOF

# Get applications list
if [ -n "${CI_APPS:-}" ]; then
  apps="$CI_APPS"
else
  apps=$(./bin/epmp --short 2>/dev/null)
fi

# Get systems list
if [ -n "${CI_SYSTEMS:-}" ]; then
  systems="$CI_SYSTEMS"
else
  systems="alt:sisyphus debian:bookworm"
fi

#
# -------- Stage: Download test --------
#
for app in $apps; do
  safe_app="${app//[^a-zA-Z0-9_]/_}"

  cat <<EOF
download_${safe_app}_p11:
  stage: download_test
  allow_failure: true
  image: alt:p11
  tags:
    - access
  before_script:
    - ./bin/epm -y repo set etersoft
    - ./bin/epm update
    - ./bin/epm -y install wget glibc-pthread file patool
    - ./bin/epm play --auto --ipfs kubo
  script:
    - bash ./ci/prepare_ipfs.sh ${app}
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - ipfs

EOF
done

#
# -------- Stage: Publish_download_logs --------
#
cat <<'EOF'
publish_download_logs:
  stage: publish_download_logs
  image: alt:p11
  tags:
    - access
  when: always
  dependencies:
EOF
for app in $apps; do
  safe_app="${app//[^a-zA-Z0-9_]/_}"
  cat <<EOF
    - download_${safe_app}_p11
EOF
done
cat <<'EOF'
  before_script:
    - ./bin/epm -y repo set etersoft
    - ./bin/epm update
    - ./bin/epm -y install git rsync
  script:
    - echo "Publishing logs and IPFS DB"
    - ls -R ipfs
    - bash ./ci/push-ipfs-db.sh
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - ipfs

EOF

#
# -------- Stage: test templates --------
#
cat <<'EOF'
.test_template: &test_template
  stage: test
  allow_failure: true
  tags:
    - access
  dependencies:
    - publish_download_logs
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - epm-results

.test_sisyphus: &test_sisyphus
  image: alt:sisyphus
  before_script:
    - ./bin/epm -y repo set etersoft
    - ./bin/epm update
    - ./bin/epm -y install wget glibc-pthread file
    - mkdir -p /var/lib/eepm
    - cp ipfs/eget-ipfs-db.txt /var/lib/eepm/eget-ipfs-db.txt

.test_debian: &test_debian
  image: debian:bookworm
  before_script:
    - ./bin/epm update
    - ./bin/epm install -y bash wget ca-certificates coreutils file
    - mkdir -p /var/lib/eepm
    - cp ipfs/eget-ipfs-db.txt /var/lib/eepm/eget-ipfs-db.txt

EOF

#
# -------- Stage: test (consumers) --------
#
for app in $apps; do
  safe_app="${app//[^a-zA-Z0-9_]/_}"

  for system in $systems; do
    case "$system" in
      alt:sisyphus)
        cat <<EOF
test_${safe_app}_sisyphus:
  <<: [*test_template, *test_sisyphus]
  script:
    - bash ./ci/run_one_ci.sh ${app}

EOF
        ;;
      debian:bookworm)
        cat <<EOF
test_${safe_app}_debian:
  <<: [*test_template, *test_debian]
  script:
    - bash ./ci/run_one_ci.sh ${app}

EOF
        ;;
      *)
        echo "ERROR: unknown system '$system' (use alt:sisyphus or debian:bookworm)" >&2
        exit 1
        ;;
    esac
  done
done

#
# -------- Stage: summary --------
#
cat <<'EOF'
summary_ci:
  stage: summary
  image: alt:p11
  tags:
    - access
  when: always
  before_script:
    - ./bin/epm -y repo set etersoft
    - ./bin/epm update
    - ./bin/epm -y install git rsync
  script:
    - bash ./ci/push-results-ci.sh

EOF
